### ISSUE TITLE
Need help for designing windows input UI in scss

### ISSUE THREAD

**Issue by sptutusukanta** [sptutusukanta/PlatinUI#1]
This project is using compass scss to generate all css. I need to mimic the exact behavior and design of windows text input field.

You can check how the button looks exactly same as Windows's buttons in the example page. I need the same for Windows text input fields.

Thanks.

**Comment by galczo5** [comment]
I'll can try do it after work.

**Comment by sptutusukanta** [comment]
@galczo5 Thank you.

**Comment by galczo5** [comment]
I've made PR: https://github.com/sptutusukanta/PlatinUI/pull/2

I'm not sure if the result is what you expected, but it looks like text inputs on my wife's Win8 computer.

![2017-09-28-205524_3840x1080_scrot](https://user-images.githubusercontent.com/6080725/30985503-a2319dca-a490-11e7-8b84-ac3d2bec6b36.png)

**Comment by sptutusukanta** [comment]
@galczo5 Yes, it is good. Thanks. I'll close this issue now.
